name: Build SwiftShader

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout workflow files
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Clone SwiftShader repository
      run: git clone --recursive https://swiftshader.googlesource.com/SwiftShader D:/a/build-vulkan/swiftshader

    - name: List files in SwiftShader directory
      run: dir D:/a/build-vulkan/swiftshader

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

    - name: Setup Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure project
      run: cmake -B build -S D:/a/build-vulkan/swiftshader

    - name: Build SwiftShader
      run: cmake --build build --parallel

      - name: List files in SwiftShader directory
      run: dir

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: swiftshader-build
        path: build
